-- 코드를 입력하세요
SELECT AIN.ANIMAL_ID, AIN.ANIMAL_TYPE, AIN.NAME
FROM ANIMAL_INS AIN
INNER JOIN ANIMAL_OUTS AOUT
ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID 
WHERE AIN.SEX_UPON_INTAKE LIKE 'Intact %'
AND AOUT.SEX_UPON_OUTCOME LIKE 'Spayed Female' OR AIN.SEX_UPON_INTAKE LIKE 'Intact %'
AND AOUT.SEX_UPON_OUTCOME LIKE 'Neutered Male'
ORDER BY AIN.ANIMAL_ID ASC