-- 코드를 입력하세요
SELECT B.CATEGORY,SUM(BS.SALES) AS TOTAL_SALES 
FROM BOOK B, BOOK_SALES BS
WHERE B.BOOK_ID = BS.BOOK_ID AND YEAR(BS.SALES_DATE) = '2022' AND MONTH(BS.SALES_DATE) ='1' 
GROUP BY CATEGORY
ORDER BY CATEGORY